// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef _UI_COMP_MAINBUTTONTEMPLATE_H
#define _UI_COMP_MAINBUTTONTEMPLATE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MainButtonTemplate
#define UI_COMP_MAINBUTTONTEMPLATE_MAINBUTTONTEMPLATE 0
#define _UI_COMP_MAINBUTTONTEMPLATE_NUM 1
lv_obj_t * ui_MainButtonTemplate_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
