// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

// COMPONENT MainButtonTemplate

lv_obj_t * ui_MainButtonTemplate_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MainButtonTemplate;
    cui_MainButtonTemplate = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_MainButtonTemplate, 81);
    lv_obj_set_height(cui_MainButtonTemplate, 40);
    lv_obj_set_x(cui_MainButtonTemplate, -113);
    lv_obj_set_y(cui_MainButtonTemplate, 95);
    lv_obj_set_align(cui_MainButtonTemplate, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_MainButtonTemplate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_MainButtonTemplate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(cui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(cui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(cui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(cui_MainButtonTemplate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_MainButtonTemplate, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAINBUTTONTEMPLATE_NUM);
    children[UI_COMP_MAINBUTTONTEMPLATE_MAINBUTTONTEMPLATE] = cui_MainButtonTemplate;
    lv_obj_add_event_cb(cui_MainButtonTemplate, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MainButtonTemplate, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MainButtonTemplate_create_hook(cui_MainButtonTemplate);
    return cui_MainButtonTemplate;
}

