// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef UI_DEVSCREENR_H
#define UI_DEVSCREENR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DevScreenR
extern void ui_DevScreenR_screen_init(void);
extern void ui_DevScreenR_screen_destroy(void);
extern lv_obj_t * ui_DevScreenR;
extern lv_obj_t * ui_DevTabViewR;
extern lv_obj_t * ui_FSRTabR;
extern lv_obj_t * ui_FSRIndexLabelR;
extern lv_obj_t * ui_FSRReadingsLabelR;
extern lv_obj_t * ui_FSRBarContainerR;
extern lv_obj_t * ui_FSR0BarR;
extern lv_obj_t * ui_FSR1BarR;
extern lv_obj_t * ui_FSR2BarR;
extern lv_obj_t * ui_FSR3BarR;
extern lv_obj_t * ui_FSR4BarR;
extern lv_obj_t * ui_FlexTabR;
extern lv_obj_t * ui_FlexIndexLabelR;
extern lv_obj_t * ui_FlexReadingsLabelR;
extern lv_obj_t * ui_FlexBarContainerR;
extern lv_obj_t * ui_Flex5BarR;
extern lv_obj_t * ui_Flex6BarR;
extern lv_obj_t * ui_Flex7BarR;
extern lv_obj_t * ui_Flex8BarR;
extern lv_obj_t * ui_Flex9BarR;
extern lv_obj_t * ui_Flex10BarR;
extern lv_obj_t * ui_Flex11BarR;
extern lv_obj_t * ui_IMUTabR;
extern lv_obj_t * ui_IMUYawRollLabelR;
extern void ui_event_DevBackButton(lv_event_t * e);
extern lv_obj_t * ui_DevBackButton;
extern lv_obj_t * ui_DevBackButtonText;
extern lv_obj_t * ui_DevMiniStatusBarR;
extern lv_obj_t * ui_DevMiniConStatusLabelR;
extern lv_obj_t * ui_DevMiniModeLabelR;
extern lv_obj_t * ui_DevMiniBarBatteryContainerR;
extern lv_obj_t * ui_RDevMiniBatteryLabelL;
extern lv_obj_t * ui_RDevMiniBatteryLevelLabelL;
extern lv_obj_t * ui_RDevMiniBatteryLabelR;
extern lv_obj_t * ui_RDevMiniBatteryLevelLabelR;
extern void ui_event_DevScreenRButtonRight(lv_event_t * e);
extern lv_obj_t * ui_DevScreenRButtonRight;
extern lv_obj_t * ui_DevScreenRButtonRightLabel;
extern lv_obj_t * ui_DevScreenRMainLabelPanel;
extern lv_obj_t * ui_DevScreenRMainLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

