// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_DevScreenL = NULL;
lv_obj_t * ui_DevTabViewL = NULL;
lv_obj_t * ui_FSRTabL = NULL;
lv_obj_t * ui_FSRIndexLabelL = NULL;
lv_obj_t * ui_FSRReadingsLabelL = NULL;
lv_obj_t * ui_FSRBarContainerL = NULL;
lv_obj_t * ui_FSR0BarL = NULL;
lv_obj_t * ui_FSR1BarL = NULL;
lv_obj_t * ui_FSR2BarL = NULL;
lv_obj_t * ui_FSR3BarL = NULL;
lv_obj_t * ui_FSR4BarL = NULL;
lv_obj_t * ui_FlexTabL = NULL;
lv_obj_t * ui_FlexIndexLabelL = NULL;
lv_obj_t * ui_FlexReadingsLabelL = NULL;
lv_obj_t * ui_FlexBarContainerL = NULL;
lv_obj_t * ui_Flex5BarL = NULL;
lv_obj_t * ui_Flex6BarL = NULL;
lv_obj_t * ui_Flex7BarL = NULL;
lv_obj_t * ui_Flex8BarL = NULL;
lv_obj_t * ui_Flex9BarL = NULL;
lv_obj_t * ui_Flex10BarL = NULL;
lv_obj_t * ui_Flex11BarL = NULL;
lv_obj_t * ui_IMUTabL = NULL;
lv_obj_t * ui_IMUYawRollLabelL = NULL;
lv_obj_t * ui_DevMiniStatusBarL = NULL;
lv_obj_t * ui_DevMiniConStatusLabelL = NULL;
lv_obj_t * ui_DevMiniModeLabelL = NULL;
lv_obj_t * ui_DevMiniBarBatteryContainerL = NULL;
lv_obj_t * ui_LDevMiniBatteryLabelL = NULL;
lv_obj_t * ui_LDevMiniBatteryLevelLabelL = NULL;
lv_obj_t * ui_LDevMiniBatteryLabelR = NULL;
lv_obj_t * ui_LDevMiniBatteryLevelLabelR = NULL;
lv_obj_t * ui_DevScreenLButtonRight = NULL;
lv_obj_t * ui_DevScreenLButtonRightLabel = NULL;
lv_obj_t * ui_DevScreenLButtonLeft = NULL;
lv_obj_t * ui_DevScreenLButtonLeftLabel = NULL;
lv_obj_t * ui_DevScreenLMainLabelPanel = NULL;
lv_obj_t * ui_DevScreenLMainLabel = NULL;
// event funtions
void ui_event_DevScreenLButtonLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DevScreenR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DevScreenR_screen_init);
    }
}

// build funtions

void ui_DevScreenL_screen_init(void)
{
    ui_DevScreenL = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DevScreenL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DevTabViewL = lv_tabview_create(ui_DevScreenL, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_DevTabViewL, 297);
    lv_obj_set_height(ui_DevTabViewL, 166);
    lv_obj_set_x(ui_DevTabViewL, 0);
    lv_obj_set_y(ui_DevTabViewL, 24);
    lv_obj_set_align(ui_DevTabViewL, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_DevTabViewL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_DevTabViewL, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DevTabViewL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DevTabViewL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DevTabViewL, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DevTabViewL), lv_color_hex(0x808080),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DevTabViewL), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_DevTabViewL), LV_TEXT_ALIGN_CENTER,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_DevTabViewL), &lv_font_montserrat_14,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_DevTabViewL), lv_color_hex(0x3F71FF),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_DevTabViewL), 40,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_DevTabViewL), lv_color_hex(0x808080),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_DevTabViewL), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_DevTabViewL), 4,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_DevTabViewL), LV_BORDER_SIDE_NONE,
                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DevTabViewL), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DevTabViewL), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewL),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewL),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewL),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewL),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_DevTabViewL), 4,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_DevTabViewL), LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_FSRTabL = lv_tabview_add_tab(ui_DevTabViewL, "FSR");
    lv_obj_clear_flag(ui_FSRTabL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FSRIndexLabelL = lv_label_create(ui_FSRTabL);
    lv_obj_set_width(ui_FSRIndexLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FSRIndexLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FSRIndexLabelL, -4);
    lv_obj_set_y(ui_FSRIndexLabelL, -5);
    lv_label_set_text(ui_FSRIndexLabelL, "0 \n1 \n2 \n3 \n4 ");
    lv_obj_clear_flag(ui_FSRIndexLabelL,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FSRIndexLabelL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FSRIndexLabelL, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FSRIndexLabelL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FSRIndexLabelL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_FSRIndexLabelL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_FSRIndexLabelL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FSRIndexLabelL, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSRReadingsLabelL = lv_label_create(ui_FSRTabL);
    lv_obj_set_width(ui_FSRReadingsLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FSRReadingsLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FSRReadingsLabelL, 22);
    lv_obj_set_y(ui_FSRReadingsLabelL, -3);
    lv_label_set_text(ui_FSRReadingsLabelL, "4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)");
    lv_obj_clear_flag(ui_FSRReadingsLabelL,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FSRReadingsLabelL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FSRReadingsLabelL, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FSRReadingsLabelL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSRBarContainerL = lv_obj_create(ui_FSRTabL);
    lv_obj_remove_style_all(ui_FSRBarContainerL);
    lv_obj_set_width(ui_FSRBarContainerL, 153);
    lv_obj_set_height(ui_FSRBarContainerL, 110);
    lv_obj_set_x(ui_FSRBarContainerL, -2);
    lv_obj_set_y(ui_FSRBarContainerL, 1);
    lv_obj_set_align(ui_FSRBarContainerL, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_FSRBarContainerL, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FSRBarContainerL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FSRBarContainerL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_FSRBarContainerL, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FSRBarContainerL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSR0BarL = lv_bar_create(ui_FSRBarContainerL);
    lv_bar_set_range(ui_FSR0BarL, 0, 4095);
    lv_bar_set_value(ui_FSR0BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR0BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR0BarL, 146);
    lv_obj_set_height(ui_FSR0BarL, 10);
    lv_obj_set_x(ui_FSR0BarL, -6);
    lv_obj_set_y(ui_FSR0BarL, -51);
    lv_obj_set_align(ui_FSR0BarL, LV_ALIGN_RIGHT_MID);

    ui_FSR1BarL = lv_bar_create(ui_FSRBarContainerL);
    lv_bar_set_range(ui_FSR1BarL, 0, 4095);
    lv_bar_set_value(ui_FSR1BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR1BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR1BarL, 146);
    lv_obj_set_height(ui_FSR1BarL, 10);
    lv_obj_set_x(ui_FSR1BarL, -6);
    lv_obj_set_y(ui_FSR1BarL, -28);
    lv_obj_set_align(ui_FSR1BarL, LV_ALIGN_RIGHT_MID);

    ui_FSR2BarL = lv_bar_create(ui_FSRBarContainerL);
    lv_bar_set_range(ui_FSR2BarL, 0, 4095);
    lv_bar_set_value(ui_FSR2BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR2BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR2BarL, 146);
    lv_obj_set_height(ui_FSR2BarL, 10);
    lv_obj_set_x(ui_FSR2BarL, -6);
    lv_obj_set_y(ui_FSR2BarL, -5);
    lv_obj_set_align(ui_FSR2BarL, LV_ALIGN_RIGHT_MID);

    ui_FSR3BarL = lv_bar_create(ui_FSRBarContainerL);
    lv_bar_set_range(ui_FSR3BarL, 0, 4095);
    lv_bar_set_value(ui_FSR3BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR3BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR3BarL, 146);
    lv_obj_set_height(ui_FSR3BarL, 10);
    lv_obj_set_x(ui_FSR3BarL, -6);
    lv_obj_set_y(ui_FSR3BarL, 18);
    lv_obj_set_align(ui_FSR3BarL, LV_ALIGN_RIGHT_MID);

    ui_FSR4BarL = lv_bar_create(ui_FSRBarContainerL);
    lv_bar_set_range(ui_FSR4BarL, 0, 4095);
    lv_bar_set_value(ui_FSR4BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR4BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR4BarL, 146);
    lv_obj_set_height(ui_FSR4BarL, 10);
    lv_obj_set_x(ui_FSR4BarL, -6);
    lv_obj_set_y(ui_FSR4BarL, 41);
    lv_obj_set_align(ui_FSR4BarL, LV_ALIGN_RIGHT_MID);

    ui_FlexTabL = lv_tabview_add_tab(ui_DevTabViewL, "Flex");

    ui_FlexIndexLabelL = lv_label_create(ui_FlexTabL);
    lv_obj_set_width(ui_FlexIndexLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlexIndexLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlexIndexLabelL, -4);
    lv_obj_set_y(ui_FlexIndexLabelL, -5);
    lv_label_set_text(ui_FlexIndexLabelL, "5\n6\n7\n8\n9\n10\n11");
    lv_obj_clear_flag(ui_FlexIndexLabelL,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FlexIndexLabelL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FlexIndexLabelL, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FlexIndexLabelL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FlexIndexLabelL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_FlexIndexLabelL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_FlexIndexLabelL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FlexIndexLabelL, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlexReadingsLabelL = lv_label_create(ui_FlexTabL);
    lv_obj_set_width(ui_FlexReadingsLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlexReadingsLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlexReadingsLabelL, 22);
    lv_obj_set_y(ui_FlexReadingsLabelL, -3);
    lv_label_set_text(ui_FlexReadingsLabelL,
                      "4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)");
    lv_obj_clear_flag(ui_FlexReadingsLabelL,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FlexReadingsLabelL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FlexReadingsLabelL, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FlexReadingsLabelL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlexBarContainerL = lv_obj_create(ui_FlexTabL);
    lv_obj_remove_style_all(ui_FlexBarContainerL);
    lv_obj_set_width(ui_FlexBarContainerL, 145);
    lv_obj_set_height(ui_FlexBarContainerL, 164);
    lv_obj_set_x(ui_FlexBarContainerL, -2);
    lv_obj_set_y(ui_FlexBarContainerL, 1);
    lv_obj_set_align(ui_FlexBarContainerL, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_FlexBarContainerL, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FlexBarContainerL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FlexBarContainerL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_FlexBarContainerL, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FlexBarContainerL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flex5BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex5BarL, 0, 4095);
    lv_bar_set_value(ui_Flex5BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex5BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex5BarL, 146);
    lv_obj_set_height(ui_Flex5BarL, 10);
    lv_obj_set_x(ui_Flex5BarL, -6);
    lv_obj_set_y(ui_Flex5BarL, -51);
    lv_obj_set_align(ui_Flex5BarL, LV_ALIGN_RIGHT_MID);

    ui_Flex6BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex6BarL, 0, 4095);
    lv_bar_set_value(ui_Flex6BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex6BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex6BarL, 146);
    lv_obj_set_height(ui_Flex6BarL, 10);
    lv_obj_set_x(ui_Flex6BarL, -6);
    lv_obj_set_y(ui_Flex6BarL, -28);
    lv_obj_set_align(ui_Flex6BarL, LV_ALIGN_RIGHT_MID);

    ui_Flex7BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex7BarL, 0, 4095);
    lv_bar_set_value(ui_Flex7BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex7BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex7BarL, 146);
    lv_obj_set_height(ui_Flex7BarL, 10);
    lv_obj_set_x(ui_Flex7BarL, -6);
    lv_obj_set_y(ui_Flex7BarL, -5);
    lv_obj_set_align(ui_Flex7BarL, LV_ALIGN_RIGHT_MID);

    ui_Flex8BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex8BarL, 0, 4095);
    lv_bar_set_value(ui_Flex8BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex8BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex8BarL, 146);
    lv_obj_set_height(ui_Flex8BarL, 10);
    lv_obj_set_x(ui_Flex8BarL, -6);
    lv_obj_set_y(ui_Flex8BarL, 18);
    lv_obj_set_align(ui_Flex8BarL, LV_ALIGN_RIGHT_MID);

    ui_Flex9BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex9BarL, 0, 4095);
    lv_bar_set_value(ui_Flex9BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex9BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex9BarL, 146);
    lv_obj_set_height(ui_Flex9BarL, 10);
    lv_obj_set_x(ui_Flex9BarL, -6);
    lv_obj_set_y(ui_Flex9BarL, 41);
    lv_obj_set_align(ui_Flex9BarL, LV_ALIGN_RIGHT_MID);

    ui_Flex10BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex10BarL, 0, 4095);
    lv_bar_set_value(ui_Flex10BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex10BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex10BarL, 146);
    lv_obj_set_height(ui_Flex10BarL, 10);
    lv_obj_set_x(ui_Flex10BarL, -6);
    lv_obj_set_y(ui_Flex10BarL, 64);
    lv_obj_set_align(ui_Flex10BarL, LV_ALIGN_RIGHT_MID);

    ui_Flex11BarL = lv_bar_create(ui_FlexBarContainerL);
    lv_bar_set_range(ui_Flex11BarL, 0, 4095);
    lv_bar_set_value(ui_Flex11BarL, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex11BarL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex11BarL, 146);
    lv_obj_set_height(ui_Flex11BarL, 10);
    lv_obj_set_x(ui_Flex11BarL, -6);
    lv_obj_set_y(ui_Flex11BarL, 87);
    lv_obj_set_align(ui_Flex11BarL, LV_ALIGN_RIGHT_MID);

    ui_IMUTabL = lv_tabview_add_tab(ui_DevTabViewL, "IMU");

    ui_IMUYawRollLabelL = lv_label_create(ui_IMUTabL);
    lv_obj_set_width(ui_IMUYawRollLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IMUYawRollLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IMUYawRollLabelL, -4);
    lv_obj_set_y(ui_IMUYawRollLabelL, -3);
    lv_label_set_text(ui_IMUYawRollLabelL, "Yaw:\nRoll:");

    ui_DevMiniStatusBarL = lv_obj_create(ui_DevScreenL);
    lv_obj_set_width(ui_DevMiniStatusBarL, 189);
    lv_obj_set_height(ui_DevMiniStatusBarL, 40);
    lv_obj_set_x(ui_DevMiniStatusBarL, -5);
    lv_obj_set_y(ui_DevMiniStatusBarL, -3);
    lv_obj_set_align(ui_DevMiniStatusBarL, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DevMiniStatusBarL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevMiniStatusBarL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevMiniStatusBarL, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevMiniConStatusLabelL = lv_label_create(ui_DevMiniStatusBarL);
    lv_obj_set_width(ui_DevMiniConStatusLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevMiniConStatusLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevMiniConStatusLabelL, -3);
    lv_obj_set_y(ui_DevMiniConStatusLabelL, -1);
    lv_label_set_text(ui_DevMiniConStatusLabelL, "ESP-NOW");
    lv_obj_set_style_text_color(ui_DevMiniConStatusLabelL, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevMiniConStatusLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevMiniConStatusLabelL, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevMiniConStatusLabelL, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevMiniModeLabelL = lv_label_create(ui_DevMiniStatusBarL);
    lv_obj_set_width(ui_DevMiniModeLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevMiniModeLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevMiniModeLabelL, 15);
    lv_obj_set_y(ui_DevMiniModeLabelL, 0);
    lv_obj_set_align(ui_DevMiniModeLabelL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevMiniModeLabelL, "0");
    lv_obj_clear_flag(ui_DevMiniModeLabelL,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DevMiniModeLabelL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevMiniModeLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevMiniModeLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevMiniModeLabelL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevMiniBarBatteryContainerL = lv_obj_create(ui_DevMiniStatusBarL);
    lv_obj_remove_style_all(ui_DevMiniBarBatteryContainerL);
    lv_obj_set_width(ui_DevMiniBarBatteryContainerL, 40);
    lv_obj_set_height(ui_DevMiniBarBatteryContainerL, 29);
    lv_obj_set_x(ui_DevMiniBarBatteryContainerL, 9);
    lv_obj_set_y(ui_DevMiniBarBatteryContainerL, 9);
    lv_obj_set_align(ui_DevMiniBarBatteryContainerL, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DevMiniBarBatteryContainerL,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_LDevMiniBatteryLabelL = lv_label_create(ui_DevMiniBarBatteryContainerL);
    lv_obj_set_width(ui_LDevMiniBatteryLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LDevMiniBatteryLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LDevMiniBatteryLabelL, -30);
    lv_obj_set_y(ui_LDevMiniBatteryLabelL, -6);
    lv_obj_set_align(ui_LDevMiniBatteryLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LDevMiniBatteryLabelL, "L:");
    lv_obj_set_style_text_color(ui_LDevMiniBatteryLabelL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LDevMiniBatteryLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LDevMiniBatteryLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LDevMiniBatteryLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LDevMiniBatteryLevelLabelL = lv_label_create(ui_DevMiniBarBatteryContainerL);
    lv_obj_set_width(ui_LDevMiniBatteryLevelLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LDevMiniBatteryLevelLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LDevMiniBatteryLevelLabelL, 0);
    lv_obj_set_y(ui_LDevMiniBatteryLevelLabelL, -6);
    lv_obj_set_align(ui_LDevMiniBatteryLevelLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LDevMiniBatteryLevelLabelL, "100%");
    lv_obj_set_style_text_color(ui_LDevMiniBatteryLevelLabelL, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LDevMiniBatteryLevelLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LDevMiniBatteryLevelLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LDevMiniBatteryLevelLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LDevMiniBatteryLabelR = lv_label_create(ui_DevMiniBarBatteryContainerL);
    lv_obj_set_width(ui_LDevMiniBatteryLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LDevMiniBatteryLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LDevMiniBatteryLabelR, -30);
    lv_obj_set_y(ui_LDevMiniBatteryLabelR, 9);
    lv_obj_set_align(ui_LDevMiniBatteryLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LDevMiniBatteryLabelR, "R:");
    lv_obj_set_style_text_color(ui_LDevMiniBatteryLabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LDevMiniBatteryLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LDevMiniBatteryLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LDevMiniBatteryLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LDevMiniBatteryLevelLabelR = lv_label_create(ui_DevMiniBarBatteryContainerL);
    lv_obj_set_width(ui_LDevMiniBatteryLevelLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LDevMiniBatteryLevelLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LDevMiniBatteryLevelLabelR, 0);
    lv_obj_set_y(ui_LDevMiniBatteryLevelLabelR, 9);
    lv_obj_set_align(ui_LDevMiniBatteryLevelLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LDevMiniBatteryLevelLabelR, "100%");
    lv_obj_set_style_text_color(ui_LDevMiniBatteryLevelLabelR, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LDevMiniBatteryLevelLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LDevMiniBatteryLevelLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LDevMiniBatteryLevelLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenLButtonRight = lv_btn_create(ui_DevScreenL);
    lv_obj_set_width(ui_DevScreenLButtonRight, 36);
    lv_obj_set_height(ui_DevScreenLButtonRight, 40);
    lv_obj_set_x(ui_DevScreenLButtonRight, 89);
    lv_obj_set_y(ui_DevScreenLButtonRight, -3);
    lv_obj_set_align(ui_DevScreenLButtonRight, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_DevScreenLButtonRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DevScreenLButtonRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevScreenLButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenLButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenLButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevScreenLButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevScreenLButtonRight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevScreenLButtonRight, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenLButtonRightLabel = lv_label_create(ui_DevScreenLButtonRight);
    lv_obj_set_width(ui_DevScreenLButtonRightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevScreenLButtonRightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevScreenLButtonRightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevScreenLButtonRightLabel, ">");
    lv_obj_set_style_text_font(ui_DevScreenLButtonRightLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenLButtonLeft = lv_btn_create(ui_DevScreenL);
    lv_obj_set_width(ui_DevScreenLButtonLeft, 36);
    lv_obj_set_height(ui_DevScreenLButtonLeft, 40);
    lv_obj_set_x(ui_DevScreenLButtonLeft, 48);
    lv_obj_set_y(ui_DevScreenLButtonLeft, -3);
    lv_obj_set_align(ui_DevScreenLButtonLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_DevScreenLButtonLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DevScreenLButtonLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevScreenLButtonLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenLButtonLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenLButtonLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevScreenLButtonLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevScreenLButtonLeft, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevScreenLButtonLeft, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenLButtonLeftLabel = lv_label_create(ui_DevScreenLButtonLeft);
    lv_obj_set_width(ui_DevScreenLButtonLeftLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevScreenLButtonLeftLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevScreenLButtonLeftLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevScreenLButtonLeftLabel, "<");
    lv_obj_set_style_text_font(ui_DevScreenLButtonLeftLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenLMainLabelPanel = lv_obj_create(ui_DevScreenL);
    lv_obj_set_width(ui_DevScreenLMainLabelPanel, 304);
    lv_obj_set_height(ui_DevScreenLMainLabelPanel, 17);
    lv_obj_set_x(ui_DevScreenLMainLabelPanel, 0);
    lv_obj_set_y(ui_DevScreenLMainLabelPanel, 2);
    lv_obj_set_align(ui_DevScreenLMainLabelPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_DevScreenLMainLabelPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevScreenLMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenLMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenLMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevScreenLMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevScreenLMainLabelPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenLMainLabel = lv_label_create(ui_DevScreenLMainLabelPanel);
    lv_obj_set_width(ui_DevScreenLMainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevScreenLMainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevScreenLMainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevScreenLMainLabel, "GloveLeft -- ID: 0");
    lv_obj_set_style_text_font(ui_DevScreenLMainLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DevScreenLButtonLeft, ui_event_DevScreenLButtonLeft, LV_EVENT_ALL, NULL);

}

void ui_DevScreenL_screen_destroy(void)
{
    if(ui_DevScreenL) lv_obj_del(ui_DevScreenL);

    // NULL screen variables
    ui_DevScreenL = NULL;
    ui_DevTabViewL = NULL;
    ui_FSRTabL = NULL;
    ui_FSRIndexLabelL = NULL;
    ui_FSRReadingsLabelL = NULL;
    ui_FSRBarContainerL = NULL;
    ui_FSR0BarL = NULL;
    ui_FSR1BarL = NULL;
    ui_FSR2BarL = NULL;
    ui_FSR3BarL = NULL;
    ui_FSR4BarL = NULL;
    ui_FlexTabL = NULL;
    ui_FlexIndexLabelL = NULL;
    ui_FlexReadingsLabelL = NULL;
    ui_FlexBarContainerL = NULL;
    ui_Flex5BarL = NULL;
    ui_Flex6BarL = NULL;
    ui_Flex7BarL = NULL;
    ui_Flex8BarL = NULL;
    ui_Flex9BarL = NULL;
    ui_Flex10BarL = NULL;
    ui_Flex11BarL = NULL;
    ui_IMUTabL = NULL;
    ui_IMUYawRollLabelL = NULL;
    ui_DevMiniStatusBarL = NULL;
    ui_DevMiniConStatusLabelL = NULL;
    ui_DevMiniModeLabelL = NULL;
    ui_DevMiniBarBatteryContainerL = NULL;
    ui_LDevMiniBatteryLabelL = NULL;
    ui_LDevMiniBatteryLevelLabelL = NULL;
    ui_LDevMiniBatteryLabelR = NULL;
    ui_LDevMiniBatteryLevelLabelR = NULL;
    ui_DevScreenLButtonRight = NULL;
    ui_DevScreenLButtonRightLabel = NULL;
    ui_DevScreenLButtonLeft = NULL;
    ui_DevScreenLButtonLeftLabel = NULL;
    ui_DevScreenLMainLabelPanel = NULL;
    ui_DevScreenLMainLabel = NULL;

}
