// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_DevScreen = NULL;
lv_obj_t * ui_DevTabView = NULL;
lv_obj_t * ui_FSRTab = NULL;
lv_obj_t * ui_FSRIndexLabel = NULL;
lv_obj_t * ui_FSRReadingsLabel = NULL;
lv_obj_t * ui_BarContainer = NULL;
lv_obj_t * ui_FSR0Bar = NULL;
lv_obj_t * ui_FSR1Bar = NULL;
lv_obj_t * ui_FSR2Bar = NULL;
lv_obj_t * ui_FSR3Bar = NULL;
lv_obj_t * ui_FSR4Bar = NULL;
lv_obj_t * ui_FlexTab = NULL;
lv_obj_t * ui_FlexIndexLabel = NULL;
lv_obj_t * ui_FlexReadingsLabel = NULL;
lv_obj_t * ui_BarContainer2 = NULL;
lv_obj_t * ui_Flex5Bar = NULL;
lv_obj_t * ui_Flex6Bar = NULL;
lv_obj_t * ui_Flex7Bar = NULL;
lv_obj_t * ui_Flex8Bar = NULL;
lv_obj_t * ui_Flex9Bar = NULL;
lv_obj_t * ui_Flex10Bar = NULL;
lv_obj_t * ui_Flex11Bar = NULL;
lv_obj_t * ui_IMUTab = NULL;
lv_obj_t * ui_DevUIMouseCoordsLabel = NULL;
lv_obj_t * ui_IMUYawRollLabel = NULL;
lv_obj_t * ui_DevBackButton = NULL;
lv_obj_t * ui_DevBackButtonText = NULL;
lv_obj_t * ui_DevMiniStatusBar = NULL;
lv_obj_t * ui_DevConStatusLabel = NULL;
lv_obj_t * ui_DevMiniModeLabel = NULL;
lv_obj_t * ui_DevBatteryContainer = NULL;
lv_obj_t * ui_DevBatteryLabelL = NULL;
lv_obj_t * ui_DevBatteryLevelLabelL = NULL;
lv_obj_t * ui_DevBatteryLabelR = NULL;
lv_obj_t * ui_DevBatteryLevelLabelR = NULL;
// event funtions
void ui_event_DevBackButton_MainButtonTemplate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 150, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_DevScreen_screen_init(void)
{
    ui_DevScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DevScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DevTabView = lv_tabview_create(ui_DevScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_DevTabView, 297);
    lv_obj_set_height(ui_DevTabView, 184);
    lv_obj_set_x(ui_DevTabView, 0);
    lv_obj_set_y(ui_DevTabView, 5);
    lv_obj_set_align(ui_DevTabView, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_DevTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_DevTabView, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DevTabView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DevTabView, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DevTabView, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DevTabView), lv_color_hex(0x808080),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DevTabView), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_DevTabView), LV_TEXT_ALIGN_CENTER,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_DevTabView), &lv_font_montserrat_14,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_DevTabView), lv_color_hex(0x3F71FF),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_DevTabView), 40,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_DevTabView), lv_color_hex(0x808080),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_DevTabView), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_DevTabView), 4,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_DevTabView), LV_BORDER_SIDE_NONE,
                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DevTabView), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DevTabView), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabView),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabView),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabView),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabView),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_DevTabView), 4,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_DevTabView), LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_FSRTab = lv_tabview_add_tab(ui_DevTabView, "FSR");
    lv_obj_clear_flag(ui_FSRTab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FSRIndexLabel = lv_label_create(ui_FSRTab);
    lv_obj_set_width(ui_FSRIndexLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FSRIndexLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FSRIndexLabel, -4);
    lv_obj_set_y(ui_FSRIndexLabel, -5);
    lv_label_set_text(ui_FSRIndexLabel, "0 \n1 \n2 \n3 \n4 ");
    lv_obj_clear_flag(ui_FSRIndexLabel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FSRIndexLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FSRIndexLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FSRIndexLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FSRIndexLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_FSRIndexLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_FSRIndexLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FSRIndexLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSRReadingsLabel = lv_label_create(ui_FSRTab);
    lv_obj_set_width(ui_FSRReadingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FSRReadingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FSRReadingsLabel, 22);
    lv_obj_set_y(ui_FSRReadingsLabel, -3);
    lv_label_set_text(ui_FSRReadingsLabel, "4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)");
    lv_obj_clear_flag(ui_FSRReadingsLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FSRReadingsLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FSRReadingsLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FSRReadingsLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarContainer = lv_obj_create(ui_FSRTab);
    lv_obj_remove_style_all(ui_BarContainer);
    lv_obj_set_width(ui_BarContainer, 153);
    lv_obj_set_height(ui_BarContainer, 110);
    lv_obj_set_x(ui_BarContainer, -2);
    lv_obj_set_y(ui_BarContainer, 1);
    lv_obj_set_align(ui_BarContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BarContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BarContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BarContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_BarContainer, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BarContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSR0Bar = lv_bar_create(ui_BarContainer);
    lv_bar_set_range(ui_FSR0Bar, 0, 4095);
    lv_bar_set_value(ui_FSR0Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR0Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR0Bar, 146);
    lv_obj_set_height(ui_FSR0Bar, 10);
    lv_obj_set_x(ui_FSR0Bar, -6);
    lv_obj_set_y(ui_FSR0Bar, -51);
    lv_obj_set_align(ui_FSR0Bar, LV_ALIGN_RIGHT_MID);

    ui_FSR1Bar = lv_bar_create(ui_BarContainer);
    lv_bar_set_range(ui_FSR1Bar, 0, 4095);
    lv_bar_set_value(ui_FSR1Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR1Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR1Bar, 146);
    lv_obj_set_height(ui_FSR1Bar, 10);
    lv_obj_set_x(ui_FSR1Bar, -6);
    lv_obj_set_y(ui_FSR1Bar, -28);
    lv_obj_set_align(ui_FSR1Bar, LV_ALIGN_RIGHT_MID);

    ui_FSR2Bar = lv_bar_create(ui_BarContainer);
    lv_bar_set_range(ui_FSR2Bar, 0, 4095);
    lv_bar_set_value(ui_FSR2Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR2Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR2Bar, 146);
    lv_obj_set_height(ui_FSR2Bar, 10);
    lv_obj_set_x(ui_FSR2Bar, -6);
    lv_obj_set_y(ui_FSR2Bar, -5);
    lv_obj_set_align(ui_FSR2Bar, LV_ALIGN_RIGHT_MID);

    ui_FSR3Bar = lv_bar_create(ui_BarContainer);
    lv_bar_set_range(ui_FSR3Bar, 0, 4095);
    lv_bar_set_value(ui_FSR3Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR3Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR3Bar, 146);
    lv_obj_set_height(ui_FSR3Bar, 10);
    lv_obj_set_x(ui_FSR3Bar, -6);
    lv_obj_set_y(ui_FSR3Bar, 18);
    lv_obj_set_align(ui_FSR3Bar, LV_ALIGN_RIGHT_MID);

    ui_FSR4Bar = lv_bar_create(ui_BarContainer);
    lv_bar_set_range(ui_FSR4Bar, 0, 4095);
    lv_bar_set_value(ui_FSR4Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR4Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR4Bar, 146);
    lv_obj_set_height(ui_FSR4Bar, 10);
    lv_obj_set_x(ui_FSR4Bar, -6);
    lv_obj_set_y(ui_FSR4Bar, 41);
    lv_obj_set_align(ui_FSR4Bar, LV_ALIGN_RIGHT_MID);

    ui_FlexTab = lv_tabview_add_tab(ui_DevTabView, "Flex");

    ui_FlexIndexLabel = lv_label_create(ui_FlexTab);
    lv_obj_set_width(ui_FlexIndexLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlexIndexLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlexIndexLabel, -4);
    lv_obj_set_y(ui_FlexIndexLabel, -5);
    lv_label_set_text(ui_FlexIndexLabel, "5\n6\n7\n8\n9\n10\n11");
    lv_obj_clear_flag(ui_FlexIndexLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FlexIndexLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FlexIndexLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FlexIndexLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FlexIndexLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_FlexIndexLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_FlexIndexLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FlexIndexLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlexReadingsLabel = lv_label_create(ui_FlexTab);
    lv_obj_set_width(ui_FlexReadingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlexReadingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlexReadingsLabel, 22);
    lv_obj_set_y(ui_FlexReadingsLabel, -3);
    lv_label_set_text(ui_FlexReadingsLabel,
                      "4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)");
    lv_obj_clear_flag(ui_FlexReadingsLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FlexReadingsLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FlexReadingsLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FlexReadingsLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarContainer2 = lv_obj_create(ui_FlexTab);
    lv_obj_remove_style_all(ui_BarContainer2);
    lv_obj_set_width(ui_BarContainer2, 145);
    lv_obj_set_height(ui_BarContainer2, 164);
    lv_obj_set_x(ui_BarContainer2, -2);
    lv_obj_set_y(ui_BarContainer2, 1);
    lv_obj_set_align(ui_BarContainer2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BarContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BarContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BarContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_BarContainer2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BarContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flex5Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex5Bar, 0, 4095);
    lv_bar_set_value(ui_Flex5Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex5Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex5Bar, 146);
    lv_obj_set_height(ui_Flex5Bar, 10);
    lv_obj_set_x(ui_Flex5Bar, -6);
    lv_obj_set_y(ui_Flex5Bar, -51);
    lv_obj_set_align(ui_Flex5Bar, LV_ALIGN_RIGHT_MID);

    ui_Flex6Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex6Bar, 0, 4095);
    lv_bar_set_value(ui_Flex6Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex6Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex6Bar, 146);
    lv_obj_set_height(ui_Flex6Bar, 10);
    lv_obj_set_x(ui_Flex6Bar, -6);
    lv_obj_set_y(ui_Flex6Bar, -28);
    lv_obj_set_align(ui_Flex6Bar, LV_ALIGN_RIGHT_MID);

    ui_Flex7Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex7Bar, 0, 4095);
    lv_bar_set_value(ui_Flex7Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex7Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex7Bar, 146);
    lv_obj_set_height(ui_Flex7Bar, 10);
    lv_obj_set_x(ui_Flex7Bar, -6);
    lv_obj_set_y(ui_Flex7Bar, -5);
    lv_obj_set_align(ui_Flex7Bar, LV_ALIGN_RIGHT_MID);

    ui_Flex8Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex8Bar, 0, 4095);
    lv_bar_set_value(ui_Flex8Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex8Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex8Bar, 146);
    lv_obj_set_height(ui_Flex8Bar, 10);
    lv_obj_set_x(ui_Flex8Bar, -6);
    lv_obj_set_y(ui_Flex8Bar, 18);
    lv_obj_set_align(ui_Flex8Bar, LV_ALIGN_RIGHT_MID);

    ui_Flex9Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex9Bar, 0, 4095);
    lv_bar_set_value(ui_Flex9Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex9Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex9Bar, 146);
    lv_obj_set_height(ui_Flex9Bar, 10);
    lv_obj_set_x(ui_Flex9Bar, -6);
    lv_obj_set_y(ui_Flex9Bar, 41);
    lv_obj_set_align(ui_Flex9Bar, LV_ALIGN_RIGHT_MID);

    ui_Flex10Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex10Bar, 0, 4095);
    lv_bar_set_value(ui_Flex10Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex10Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex10Bar, 146);
    lv_obj_set_height(ui_Flex10Bar, 10);
    lv_obj_set_x(ui_Flex10Bar, -6);
    lv_obj_set_y(ui_Flex10Bar, 64);
    lv_obj_set_align(ui_Flex10Bar, LV_ALIGN_RIGHT_MID);

    ui_Flex11Bar = lv_bar_create(ui_BarContainer2);
    lv_bar_set_range(ui_Flex11Bar, 0, 4095);
    lv_bar_set_value(ui_Flex11Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex11Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex11Bar, 146);
    lv_obj_set_height(ui_Flex11Bar, 10);
    lv_obj_set_x(ui_Flex11Bar, -6);
    lv_obj_set_y(ui_Flex11Bar, 87);
    lv_obj_set_align(ui_Flex11Bar, LV_ALIGN_RIGHT_MID);

    ui_IMUTab = lv_tabview_add_tab(ui_DevTabView, "Mouse");

    ui_DevUIMouseCoordsLabel = lv_label_create(ui_IMUTab);
    lv_obj_set_width(ui_DevUIMouseCoordsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevUIMouseCoordsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevUIMouseCoordsLabel, 226);
    lv_obj_set_y(ui_DevUIMouseCoordsLabel, -6);
    lv_label_set_text(ui_DevUIMouseCoordsLabel, "X: 999\nY: 999");

    ui_IMUYawRollLabel = lv_label_create(ui_IMUTab);
    lv_obj_set_width(ui_IMUYawRollLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IMUYawRollLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IMUYawRollLabel, -4);
    lv_obj_set_y(ui_IMUYawRollLabel, -3);
    lv_label_set_text(ui_IMUYawRollLabel, "Yaw:\nRoll:");

    ui_DevBackButton = ui_MainButtonTemplate_create(ui_DevScreen);
    lv_obj_set_x(ui_DevBackButton, -113);
    lv_obj_set_y(ui_DevBackButton, 97);

    ui_DevBackButtonText = lv_label_create(ui_DevBackButton);
    lv_obj_set_width(ui_DevBackButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevBackButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevBackButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevBackButtonText, "Back");

    lv_obj_move_to_index(ui_DevBackButtonText, 0);
    ui_DevMiniStatusBar = lv_obj_create(ui_DevScreen);
    lv_obj_set_width(ui_DevMiniStatusBar, 189);
    lv_obj_set_height(ui_DevMiniStatusBar, 40);
    lv_obj_set_x(ui_DevMiniStatusBar, -5);
    lv_obj_set_y(ui_DevMiniStatusBar, -3);
    lv_obj_set_align(ui_DevMiniStatusBar, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DevMiniStatusBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevMiniStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevMiniStatusBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevMiniStatusBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevConStatusLabel = lv_label_create(ui_DevMiniStatusBar);
    lv_obj_set_width(ui_DevConStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevConStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevConStatusLabel, -3);
    lv_obj_set_y(ui_DevConStatusLabel, -1);
    lv_label_set_text(ui_DevConStatusLabel, "ESP-NOW");
    lv_obj_set_style_text_color(ui_DevConStatusLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevConStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevConStatusLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevConStatusLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevMiniModeLabel = lv_label_create(ui_DevMiniStatusBar);
    lv_obj_set_width(ui_DevMiniModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevMiniModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevMiniModeLabel, 15);
    lv_obj_set_y(ui_DevMiniModeLabel, 0);
    lv_obj_set_align(ui_DevMiniModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevMiniModeLabel, "0");
    lv_obj_clear_flag(ui_DevMiniModeLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DevMiniModeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevMiniModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevMiniModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevMiniModeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevBatteryContainer = lv_obj_create(ui_DevMiniStatusBar);
    lv_obj_remove_style_all(ui_DevBatteryContainer);
    lv_obj_set_width(ui_DevBatteryContainer, 40);
    lv_obj_set_height(ui_DevBatteryContainer, 29);
    lv_obj_set_x(ui_DevBatteryContainer, 9);
    lv_obj_set_y(ui_DevBatteryContainer, 9);
    lv_obj_set_align(ui_DevBatteryContainer, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DevBatteryContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_DevBatteryLabelL = lv_label_create(ui_DevBatteryContainer);
    lv_obj_set_width(ui_DevBatteryLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevBatteryLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevBatteryLabelL, -30);
    lv_obj_set_y(ui_DevBatteryLabelL, -6);
    lv_obj_set_align(ui_DevBatteryLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DevBatteryLabelL, "L:");
    lv_obj_set_style_text_color(ui_DevBatteryLabelL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevBatteryLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevBatteryLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevBatteryLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevBatteryLevelLabelL = lv_label_create(ui_DevBatteryContainer);
    lv_obj_set_width(ui_DevBatteryLevelLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevBatteryLevelLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevBatteryLevelLabelL, 0);
    lv_obj_set_y(ui_DevBatteryLevelLabelL, -6);
    lv_obj_set_align(ui_DevBatteryLevelLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DevBatteryLevelLabelL, "100%");
    lv_obj_set_style_text_color(ui_DevBatteryLevelLabelL, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevBatteryLevelLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevBatteryLevelLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevBatteryLevelLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevBatteryLabelR = lv_label_create(ui_DevBatteryContainer);
    lv_obj_set_width(ui_DevBatteryLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevBatteryLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevBatteryLabelR, -30);
    lv_obj_set_y(ui_DevBatteryLabelR, 9);
    lv_obj_set_align(ui_DevBatteryLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DevBatteryLabelR, "R:");
    lv_obj_set_style_text_color(ui_DevBatteryLabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevBatteryLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevBatteryLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevBatteryLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevBatteryLevelLabelR = lv_label_create(ui_DevBatteryContainer);
    lv_obj_set_width(ui_DevBatteryLevelLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevBatteryLevelLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevBatteryLevelLabelR, 0);
    lv_obj_set_y(ui_DevBatteryLevelLabelR, 9);
    lv_obj_set_align(ui_DevBatteryLevelLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DevBatteryLevelLabelR, "100%");
    lv_obj_set_style_text_color(ui_DevBatteryLevelLabelR, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevBatteryLevelLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevBatteryLevelLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevBatteryLevelLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DevBackButton, ui_event_DevBackButton_MainButtonTemplate, LV_EVENT_ALL, NULL);

}

void ui_DevScreen_screen_destroy(void)
{
    if(ui_DevScreen) lv_obj_del(ui_DevScreen);

    // NULL screen variables
    ui_DevScreen = NULL;
    ui_DevTabView = NULL;
    ui_FSRTab = NULL;
    ui_FSRIndexLabel = NULL;
    ui_FSRReadingsLabel = NULL;
    ui_BarContainer = NULL;
    ui_FSR0Bar = NULL;
    ui_FSR1Bar = NULL;
    ui_FSR2Bar = NULL;
    ui_FSR3Bar = NULL;
    ui_FSR4Bar = NULL;
    ui_FlexTab = NULL;
    ui_FlexIndexLabel = NULL;
    ui_FlexReadingsLabel = NULL;
    ui_BarContainer2 = NULL;
    ui_Flex5Bar = NULL;
    ui_Flex6Bar = NULL;
    ui_Flex7Bar = NULL;
    ui_Flex8Bar = NULL;
    ui_Flex9Bar = NULL;
    ui_Flex10Bar = NULL;
    ui_Flex11Bar = NULL;
    ui_IMUTab = NULL;
    ui_DevUIMouseCoordsLabel = NULL;
    ui_IMUYawRollLabel = NULL;
    ui_DevBackButton = NULL;
    ui_DevBackButtonText = NULL;
    ui_DevMiniStatusBar = NULL;
    ui_DevConStatusLabel = NULL;
    ui_DevMiniModeLabel = NULL;
    ui_DevBatteryContainer = NULL;
    ui_DevBatteryLabelL = NULL;
    ui_DevBatteryLevelLabelL = NULL;
    ui_DevBatteryLabelR = NULL;
    ui_DevBatteryLevelLabelR = NULL;

}
