// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef UI_DEVSCREEN_H
#define UI_DEVSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DevScreen
extern void ui_DevScreen_screen_init(void);
extern void ui_DevScreen_screen_destroy(void);
extern lv_obj_t * ui_DevScreen;
extern lv_obj_t * ui_DevTabView;
extern lv_obj_t * ui_FSRTab;
extern lv_obj_t * ui_FSRIndexLabel;
extern lv_obj_t * ui_FSRReadingsLabel;
extern lv_obj_t * ui_BarContainer;
extern lv_obj_t * ui_FSR0Bar;
extern lv_obj_t * ui_FSR1Bar;
extern lv_obj_t * ui_FSR2Bar;
extern lv_obj_t * ui_FSR3Bar;
extern lv_obj_t * ui_FSR4Bar;
extern lv_obj_t * ui_FlexTab;
extern lv_obj_t * ui_FlexIndexLabel;
extern lv_obj_t * ui_FlexReadingsLabel;
extern lv_obj_t * ui_BarContainer2;
extern lv_obj_t * ui_Flex5Bar;
extern lv_obj_t * ui_Flex6Bar;
extern lv_obj_t * ui_Flex7Bar;
extern lv_obj_t * ui_Flex8Bar;
extern lv_obj_t * ui_Flex9Bar;
extern lv_obj_t * ui_Flex10Bar;
extern lv_obj_t * ui_Flex11Bar;
extern lv_obj_t * ui_IMUTab;
extern lv_obj_t * ui_DevUIMouseCoordsLabel;
extern lv_obj_t * ui_IMUYawRollLabel;
extern void ui_event_DevBackButton_MainButtonTemplate(lv_event_t * e);
extern lv_obj_t * ui_DevBackButton;
extern lv_obj_t * ui_DevBackButtonText;
extern lv_obj_t * ui_DevMiniStatusBar;
extern lv_obj_t * ui_DevConStatusLabel;
extern lv_obj_t * ui_DevMiniModeLabel;
extern lv_obj_t * ui_DevBatteryContainer;
extern lv_obj_t * ui_DevBatteryLabelL;
extern lv_obj_t * ui_DevBatteryLevelLabelL;
extern lv_obj_t * ui_DevBatteryLabelR;
extern lv_obj_t * ui_DevBatteryLevelLabelR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

