// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_DevScreenR = NULL;
lv_obj_t * ui_DevTabViewR = NULL;
lv_obj_t * ui_FSRTabR = NULL;
lv_obj_t * ui_FSRIndexLabelR = NULL;
lv_obj_t * ui_FSRReadingsLabelR = NULL;
lv_obj_t * ui_FSRBarContainerR = NULL;
lv_obj_t * ui_FSR0BarR = NULL;
lv_obj_t * ui_FSR1BarR = NULL;
lv_obj_t * ui_FSR2BarR = NULL;
lv_obj_t * ui_FSR3BarR = NULL;
lv_obj_t * ui_FSR4BarR = NULL;
lv_obj_t * ui_FlexTabR = NULL;
lv_obj_t * ui_FlexIndexLabelR = NULL;
lv_obj_t * ui_FlexReadingsLabelR = NULL;
lv_obj_t * ui_FlexBarContainerR = NULL;
lv_obj_t * ui_Flex5BarR = NULL;
lv_obj_t * ui_Flex6BarR = NULL;
lv_obj_t * ui_Flex7BarR = NULL;
lv_obj_t * ui_Flex8BarR = NULL;
lv_obj_t * ui_Flex9BarR = NULL;
lv_obj_t * ui_Flex10BarR = NULL;
lv_obj_t * ui_Flex11BarR = NULL;
lv_obj_t * ui_IMUTabR = NULL;
lv_obj_t * ui_IMUYawRollLabelR = NULL;
lv_obj_t * ui_DevBackButton = NULL;
lv_obj_t * ui_DevBackButtonText = NULL;
lv_obj_t * ui_DevMiniStatusBarR = NULL;
lv_obj_t * ui_DevConStatusContainerR = NULL;
lv_obj_t * ui_DevLRecvLabelR = NULL;
lv_obj_t * ui_DevLRLabelR = NULL;
lv_obj_t * ui_DevRRecvLabelR = NULL;
lv_obj_t * ui_DevMiniModeLabelR = NULL;
lv_obj_t * ui_DevMiniBarBatteryContainerR = NULL;
lv_obj_t * ui_RDevMiniBatteryLabelL = NULL;
lv_obj_t * ui_RDevMiniBatteryLevelLabelL = NULL;
lv_obj_t * ui_RDevMiniBatteryLabelR = NULL;
lv_obj_t * ui_RDevMiniBatteryLevelLabelR = NULL;
lv_obj_t * ui_DevScreenRButtonRight = NULL;
lv_obj_t * ui_DevScreenRButtonRightLabel = NULL;
lv_obj_t * ui_DevScreenRMainLabelPanel = NULL;
lv_obj_t * ui_DevScreenRMainLabel = NULL;
// event funtions
void ui_event_DevBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_DevScreenRButtonRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DevScreenL, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DevScreenL_screen_init);
    }
}

// build funtions

void ui_DevScreenR_screen_init(void)
{
    ui_DevScreenR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DevScreenR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DevTabViewR = lv_tabview_create(ui_DevScreenR, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_DevTabViewR, 297);
    lv_obj_set_height(ui_DevTabViewR, 166);
    lv_obj_set_x(ui_DevTabViewR, 0);
    lv_obj_set_y(ui_DevTabViewR, 24);
    lv_obj_set_align(ui_DevTabViewR, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_DevTabViewR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_DevTabViewR, lv_color_hex(0x979797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DevTabViewR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DevTabViewR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DevTabViewR, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DevTabViewR), lv_color_hex(0x808080),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DevTabViewR), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_btns(ui_DevTabViewR), LV_TEXT_ALIGN_CENTER,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_DevTabViewR), &lv_font_montserrat_14,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_DevTabViewR), lv_color_hex(0x3F71FF),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_DevTabViewR), 40,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_DevTabViewR), lv_color_hex(0x808080),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_DevTabViewR), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_DevTabViewR), 4,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_DevTabViewR), LV_BORDER_SIDE_NONE,
                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_DevTabViewR), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_DevTabViewR), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewR),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewR),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewR),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_btns(ui_DevTabViewR),  LV_PART_ITEMS | LV_STATE_CHECKED,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_DevTabViewR), 4,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_DevTabViewR), LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_FSRTabR = lv_tabview_add_tab(ui_DevTabViewR, "FSR");
    lv_obj_clear_flag(ui_FSRTabR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FSRIndexLabelR = lv_label_create(ui_FSRTabR);
    lv_obj_set_width(ui_FSRIndexLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FSRIndexLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FSRIndexLabelR, -4);
    lv_obj_set_y(ui_FSRIndexLabelR, -5);
    lv_label_set_text(ui_FSRIndexLabelR, "0 \n1 \n2 \n3 \n4 ");
    lv_obj_clear_flag(ui_FSRIndexLabelR,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FSRIndexLabelR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FSRIndexLabelR, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FSRIndexLabelR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FSRIndexLabelR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_FSRIndexLabelR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_FSRIndexLabelR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FSRIndexLabelR, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSRReadingsLabelR = lv_label_create(ui_FSRTabR);
    lv_obj_set_width(ui_FSRReadingsLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FSRReadingsLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FSRReadingsLabelR, 22);
    lv_obj_set_y(ui_FSRReadingsLabelR, -3);
    lv_label_set_text(ui_FSRReadingsLabelR, "4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)");
    lv_obj_clear_flag(ui_FSRReadingsLabelR,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FSRReadingsLabelR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FSRReadingsLabelR, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FSRReadingsLabelR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSRBarContainerR = lv_obj_create(ui_FSRTabR);
    lv_obj_remove_style_all(ui_FSRBarContainerR);
    lv_obj_set_width(ui_FSRBarContainerR, 153);
    lv_obj_set_height(ui_FSRBarContainerR, 110);
    lv_obj_set_x(ui_FSRBarContainerR, -2);
    lv_obj_set_y(ui_FSRBarContainerR, 1);
    lv_obj_set_align(ui_FSRBarContainerR, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_FSRBarContainerR, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FSRBarContainerR, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FSRBarContainerR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_FSRBarContainerR, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FSRBarContainerR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FSR0BarR = lv_bar_create(ui_FSRBarContainerR);
    lv_bar_set_range(ui_FSR0BarR, 0, 4095);
    lv_bar_set_value(ui_FSR0BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR0BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR0BarR, 146);
    lv_obj_set_height(ui_FSR0BarR, 10);
    lv_obj_set_x(ui_FSR0BarR, -6);
    lv_obj_set_y(ui_FSR0BarR, -51);
    lv_obj_set_align(ui_FSR0BarR, LV_ALIGN_RIGHT_MID);

    ui_FSR1BarR = lv_bar_create(ui_FSRBarContainerR);
    lv_bar_set_range(ui_FSR1BarR, 0, 4095);
    lv_bar_set_value(ui_FSR1BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR1BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR1BarR, 146);
    lv_obj_set_height(ui_FSR1BarR, 10);
    lv_obj_set_x(ui_FSR1BarR, -6);
    lv_obj_set_y(ui_FSR1BarR, -28);
    lv_obj_set_align(ui_FSR1BarR, LV_ALIGN_RIGHT_MID);

    ui_FSR2BarR = lv_bar_create(ui_FSRBarContainerR);
    lv_bar_set_range(ui_FSR2BarR, 0, 4095);
    lv_bar_set_value(ui_FSR2BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR2BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR2BarR, 146);
    lv_obj_set_height(ui_FSR2BarR, 10);
    lv_obj_set_x(ui_FSR2BarR, -6);
    lv_obj_set_y(ui_FSR2BarR, -5);
    lv_obj_set_align(ui_FSR2BarR, LV_ALIGN_RIGHT_MID);

    ui_FSR3BarR = lv_bar_create(ui_FSRBarContainerR);
    lv_bar_set_range(ui_FSR3BarR, 0, 4095);
    lv_bar_set_value(ui_FSR3BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR3BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR3BarR, 146);
    lv_obj_set_height(ui_FSR3BarR, 10);
    lv_obj_set_x(ui_FSR3BarR, -6);
    lv_obj_set_y(ui_FSR3BarR, 18);
    lv_obj_set_align(ui_FSR3BarR, LV_ALIGN_RIGHT_MID);

    ui_FSR4BarR = lv_bar_create(ui_FSRBarContainerR);
    lv_bar_set_range(ui_FSR4BarR, 0, 4095);
    lv_bar_set_value(ui_FSR4BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FSR4BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FSR4BarR, 146);
    lv_obj_set_height(ui_FSR4BarR, 10);
    lv_obj_set_x(ui_FSR4BarR, -6);
    lv_obj_set_y(ui_FSR4BarR, 41);
    lv_obj_set_align(ui_FSR4BarR, LV_ALIGN_RIGHT_MID);

    ui_FlexTabR = lv_tabview_add_tab(ui_DevTabViewR, "Flex");

    ui_FlexIndexLabelR = lv_label_create(ui_FlexTabR);
    lv_obj_set_width(ui_FlexIndexLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlexIndexLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlexIndexLabelR, -4);
    lv_obj_set_y(ui_FlexIndexLabelR, -5);
    lv_label_set_text(ui_FlexIndexLabelR, "5\n6\n7\n8\n9\n10\n11");
    lv_obj_clear_flag(ui_FlexIndexLabelR,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FlexIndexLabelR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FlexIndexLabelR, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FlexIndexLabelR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_FlexIndexLabelR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_FlexIndexLabelR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_FlexIndexLabelR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FlexIndexLabelR, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlexReadingsLabelR = lv_label_create(ui_FlexTabR);
    lv_obj_set_width(ui_FlexReadingsLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlexReadingsLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlexReadingsLabelR, 22);
    lv_obj_set_y(ui_FlexReadingsLabelR, -3);
    lv_label_set_text(ui_FlexReadingsLabelR,
                      "4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)\n4096 (100%)");
    lv_obj_clear_flag(ui_FlexReadingsLabelR,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_FlexReadingsLabelR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FlexReadingsLabelR, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FlexReadingsLabelR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlexBarContainerR = lv_obj_create(ui_FlexTabR);
    lv_obj_remove_style_all(ui_FlexBarContainerR);
    lv_obj_set_width(ui_FlexBarContainerR, 145);
    lv_obj_set_height(ui_FlexBarContainerR, 164);
    lv_obj_set_x(ui_FlexBarContainerR, -2);
    lv_obj_set_y(ui_FlexBarContainerR, 1);
    lv_obj_set_align(ui_FlexBarContainerR, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_FlexBarContainerR, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FlexBarContainerR, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_FlexBarContainerR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_FlexBarContainerR, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FlexBarContainerR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flex5BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex5BarR, 0, 4095);
    lv_bar_set_value(ui_Flex5BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex5BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex5BarR, 146);
    lv_obj_set_height(ui_Flex5BarR, 10);
    lv_obj_set_x(ui_Flex5BarR, -6);
    lv_obj_set_y(ui_Flex5BarR, -51);
    lv_obj_set_align(ui_Flex5BarR, LV_ALIGN_RIGHT_MID);

    ui_Flex6BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex6BarR, 0, 4095);
    lv_bar_set_value(ui_Flex6BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex6BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex6BarR, 146);
    lv_obj_set_height(ui_Flex6BarR, 10);
    lv_obj_set_x(ui_Flex6BarR, -6);
    lv_obj_set_y(ui_Flex6BarR, -28);
    lv_obj_set_align(ui_Flex6BarR, LV_ALIGN_RIGHT_MID);

    ui_Flex7BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex7BarR, 0, 4095);
    lv_bar_set_value(ui_Flex7BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex7BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex7BarR, 146);
    lv_obj_set_height(ui_Flex7BarR, 10);
    lv_obj_set_x(ui_Flex7BarR, -6);
    lv_obj_set_y(ui_Flex7BarR, -5);
    lv_obj_set_align(ui_Flex7BarR, LV_ALIGN_RIGHT_MID);

    ui_Flex8BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex8BarR, 0, 4095);
    lv_bar_set_value(ui_Flex8BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex8BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex8BarR, 146);
    lv_obj_set_height(ui_Flex8BarR, 10);
    lv_obj_set_x(ui_Flex8BarR, -6);
    lv_obj_set_y(ui_Flex8BarR, 18);
    lv_obj_set_align(ui_Flex8BarR, LV_ALIGN_RIGHT_MID);

    ui_Flex9BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex9BarR, 0, 4095);
    lv_bar_set_value(ui_Flex9BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex9BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex9BarR, 146);
    lv_obj_set_height(ui_Flex9BarR, 10);
    lv_obj_set_x(ui_Flex9BarR, -6);
    lv_obj_set_y(ui_Flex9BarR, 41);
    lv_obj_set_align(ui_Flex9BarR, LV_ALIGN_RIGHT_MID);

    ui_Flex10BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex10BarR, 0, 4095);
    lv_bar_set_value(ui_Flex10BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex10BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex10BarR, 146);
    lv_obj_set_height(ui_Flex10BarR, 10);
    lv_obj_set_x(ui_Flex10BarR, -6);
    lv_obj_set_y(ui_Flex10BarR, 64);
    lv_obj_set_align(ui_Flex10BarR, LV_ALIGN_RIGHT_MID);

    ui_Flex11BarR = lv_bar_create(ui_FlexBarContainerR);
    lv_bar_set_range(ui_Flex11BarR, 0, 4095);
    lv_bar_set_value(ui_Flex11BarR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Flex11BarR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Flex11BarR, 146);
    lv_obj_set_height(ui_Flex11BarR, 10);
    lv_obj_set_x(ui_Flex11BarR, -6);
    lv_obj_set_y(ui_Flex11BarR, 87);
    lv_obj_set_align(ui_Flex11BarR, LV_ALIGN_RIGHT_MID);

    ui_IMUTabR = lv_tabview_add_tab(ui_DevTabViewR, "IMU");

    ui_IMUYawRollLabelR = lv_label_create(ui_IMUTabR);
    lv_obj_set_width(ui_IMUYawRollLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IMUYawRollLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IMUYawRollLabelR, -4);
    lv_obj_set_y(ui_IMUYawRollLabelR, -3);
    lv_label_set_text(ui_IMUYawRollLabelR, "Yaw:\nRoll:");

    ui_DevBackButton = lv_btn_create(ui_DevScreenR);
    lv_obj_set_width(ui_DevBackButton, 81);
    lv_obj_set_height(ui_DevBackButton, 40);
    lv_obj_set_x(ui_DevBackButton, -113);
    lv_obj_set_y(ui_DevBackButton, 97);
    lv_obj_set_align(ui_DevBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DevBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DevBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevBackButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevBackButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevBackButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevBackButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevBackButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevBackButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevBackButtonText = lv_label_create(ui_DevBackButton);
    lv_obj_set_width(ui_DevBackButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevBackButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevBackButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevBackButtonText, "Home");

    ui_DevMiniStatusBarR = lv_obj_create(ui_DevScreenR);
    lv_obj_set_width(ui_DevMiniStatusBarR, 189);
    lv_obj_set_height(ui_DevMiniStatusBarR, 40);
    lv_obj_set_x(ui_DevMiniStatusBarR, -5);
    lv_obj_set_y(ui_DevMiniStatusBarR, -3);
    lv_obj_set_align(ui_DevMiniStatusBarR, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DevMiniStatusBarR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevMiniStatusBarR, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevMiniStatusBarR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevMiniStatusBarR, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevConStatusContainerR = lv_obj_create(ui_DevMiniStatusBarR);
    lv_obj_remove_style_all(ui_DevConStatusContainerR);
    lv_obj_set_width(ui_DevConStatusContainerR, 109);
    lv_obj_set_height(ui_DevConStatusContainerR, 26);
    lv_obj_set_x(ui_DevConStatusContainerR, -3);
    lv_obj_set_y(ui_DevConStatusContainerR, 0);
    lv_obj_set_align(ui_DevConStatusContainerR, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_DevConStatusContainerR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DevLRecvLabelR = lv_label_create(ui_DevConStatusContainerR);
    lv_obj_set_width(ui_DevLRecvLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevLRecvLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevLRecvLabelR, 7);
    lv_obj_set_y(ui_DevLRecvLabelR, 9);
    lv_obj_set_align(ui_DevLRecvLabelR, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DevLRecvLabelR, "L<>RECV");
    lv_obj_set_style_text_color(ui_DevLRecvLabelR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevLRecvLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevLRecvLabelR, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevLRecvLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevLRLabelR = lv_label_create(ui_DevConStatusContainerR);
    lv_obj_set_width(ui_DevLRLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevLRLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevLRLabelR, 61);
    lv_obj_set_y(ui_DevLRLabelR, -1);
    lv_obj_set_align(ui_DevLRLabelR, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DevLRLabelR, "L<>R");
    lv_obj_set_style_text_color(ui_DevLRLabelR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevLRLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevLRLabelR, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevLRLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevRRecvLabelR = lv_label_create(ui_DevConStatusContainerR);
    lv_obj_set_width(ui_DevRRecvLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevRRecvLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevRRecvLabelR, 7);
    lv_obj_set_y(ui_DevRRecvLabelR, -7);
    lv_obj_set_align(ui_DevRRecvLabelR, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DevRRecvLabelR, "R<>RECV");
    lv_obj_set_style_text_color(ui_DevRRecvLabelR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevRRecvLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevRRecvLabelR, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevRRecvLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevMiniModeLabelR = lv_label_create(ui_DevMiniStatusBarR);
    lv_obj_set_width(ui_DevMiniModeLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevMiniModeLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DevMiniModeLabelR, 28);
    lv_obj_set_y(ui_DevMiniModeLabelR, 0);
    lv_obj_set_align(ui_DevMiniModeLabelR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevMiniModeLabelR, "0");
    lv_obj_clear_flag(ui_DevMiniModeLabelR,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DevMiniModeLabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevMiniModeLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DevMiniModeLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DevMiniModeLabelR, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevMiniBarBatteryContainerR = lv_obj_create(ui_DevMiniStatusBarR);
    lv_obj_remove_style_all(ui_DevMiniBarBatteryContainerR);
    lv_obj_set_width(ui_DevMiniBarBatteryContainerR, 40);
    lv_obj_set_height(ui_DevMiniBarBatteryContainerR, 29);
    lv_obj_set_x(ui_DevMiniBarBatteryContainerR, 9);
    lv_obj_set_y(ui_DevMiniBarBatteryContainerR, 9);
    lv_obj_set_align(ui_DevMiniBarBatteryContainerR, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_DevMiniBarBatteryContainerR,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_DevMiniBarBatteryContainerR, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevMiniBarBatteryContainerR, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevMiniBarBatteryContainerR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevMiniBarBatteryContainerR, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RDevMiniBatteryLabelL = lv_label_create(ui_DevMiniBarBatteryContainerR);
    lv_obj_set_width(ui_RDevMiniBatteryLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RDevMiniBatteryLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RDevMiniBatteryLabelL, -27);
    lv_obj_set_y(ui_RDevMiniBatteryLabelL, -5);
    lv_obj_set_align(ui_RDevMiniBatteryLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RDevMiniBatteryLabelL, "L:");
    lv_obj_set_style_text_color(ui_RDevMiniBatteryLabelL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RDevMiniBatteryLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RDevMiniBatteryLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RDevMiniBatteryLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RDevMiniBatteryLevelLabelL = lv_label_create(ui_DevMiniBarBatteryContainerR);
    lv_obj_set_width(ui_RDevMiniBatteryLevelLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RDevMiniBatteryLevelLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RDevMiniBatteryLevelLabelL, 1);
    lv_obj_set_y(ui_RDevMiniBatteryLevelLabelL, -6);
    lv_obj_set_align(ui_RDevMiniBatteryLevelLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RDevMiniBatteryLevelLabelL, "100%");
    lv_obj_set_style_text_color(ui_RDevMiniBatteryLevelLabelL, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RDevMiniBatteryLevelLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RDevMiniBatteryLevelLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RDevMiniBatteryLevelLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RDevMiniBatteryLabelR = lv_label_create(ui_DevMiniBarBatteryContainerR);
    lv_obj_set_width(ui_RDevMiniBatteryLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RDevMiniBatteryLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RDevMiniBatteryLabelR, -27);
    lv_obj_set_y(ui_RDevMiniBatteryLabelR, 9);
    lv_obj_set_align(ui_RDevMiniBatteryLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RDevMiniBatteryLabelR, "R:");
    lv_obj_set_style_text_color(ui_RDevMiniBatteryLabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RDevMiniBatteryLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RDevMiniBatteryLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RDevMiniBatteryLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RDevMiniBatteryLevelLabelR = lv_label_create(ui_DevMiniBarBatteryContainerR);
    lv_obj_set_width(ui_RDevMiniBatteryLevelLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RDevMiniBatteryLevelLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RDevMiniBatteryLevelLabelR, 1);
    lv_obj_set_y(ui_RDevMiniBatteryLevelLabelR, 9);
    lv_obj_set_align(ui_RDevMiniBatteryLevelLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RDevMiniBatteryLevelLabelR, "100%");
    lv_obj_set_style_text_color(ui_RDevMiniBatteryLevelLabelR, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RDevMiniBatteryLevelLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RDevMiniBatteryLevelLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RDevMiniBatteryLevelLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenRButtonRight = lv_btn_create(ui_DevScreenR);
    lv_obj_set_width(ui_DevScreenRButtonRight, 36);
    lv_obj_set_height(ui_DevScreenRButtonRight, 40);
    lv_obj_set_x(ui_DevScreenRButtonRight, 89);
    lv_obj_set_y(ui_DevScreenRButtonRight, -3);
    lv_obj_set_align(ui_DevScreenRButtonRight, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_DevScreenRButtonRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DevScreenRButtonRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevScreenRButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenRButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenRButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevScreenRButtonRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevScreenRButtonRight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevScreenRButtonRight, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenRButtonRightLabel = lv_label_create(ui_DevScreenRButtonRight);
    lv_obj_set_width(ui_DevScreenRButtonRightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevScreenRButtonRightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevScreenRButtonRightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevScreenRButtonRightLabel, ">");
    lv_obj_set_style_text_font(ui_DevScreenRButtonRightLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenRMainLabelPanel = lv_obj_create(ui_DevScreenR);
    lv_obj_set_width(ui_DevScreenRMainLabelPanel, 304);
    lv_obj_set_height(ui_DevScreenRMainLabelPanel, 17);
    lv_obj_set_x(ui_DevScreenRMainLabelPanel, 0);
    lv_obj_set_y(ui_DevScreenRMainLabelPanel, 2);
    lv_obj_set_align(ui_DevScreenRMainLabelPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_DevScreenRMainLabelPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevScreenRMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenRMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevScreenRMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevScreenRMainLabelPanel, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevScreenRMainLabelPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevScreenRMainLabel = lv_label_create(ui_DevScreenRMainLabelPanel);
    lv_obj_set_width(ui_DevScreenRMainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevScreenRMainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevScreenRMainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevScreenRMainLabel, "GloveRight -- ID: 1");
    lv_obj_set_style_text_font(ui_DevScreenRMainLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DevBackButton, ui_event_DevBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DevScreenRButtonRight, ui_event_DevScreenRButtonRight, LV_EVENT_ALL, NULL);

}

void ui_DevScreenR_screen_destroy(void)
{
    if(ui_DevScreenR) lv_obj_del(ui_DevScreenR);

    // NULL screen variables
    ui_DevScreenR = NULL;
    ui_DevTabViewR = NULL;
    ui_FSRTabR = NULL;
    ui_FSRIndexLabelR = NULL;
    ui_FSRReadingsLabelR = NULL;
    ui_FSRBarContainerR = NULL;
    ui_FSR0BarR = NULL;
    ui_FSR1BarR = NULL;
    ui_FSR2BarR = NULL;
    ui_FSR3BarR = NULL;
    ui_FSR4BarR = NULL;
    ui_FlexTabR = NULL;
    ui_FlexIndexLabelR = NULL;
    ui_FlexReadingsLabelR = NULL;
    ui_FlexBarContainerR = NULL;
    ui_Flex5BarR = NULL;
    ui_Flex6BarR = NULL;
    ui_Flex7BarR = NULL;
    ui_Flex8BarR = NULL;
    ui_Flex9BarR = NULL;
    ui_Flex10BarR = NULL;
    ui_Flex11BarR = NULL;
    ui_IMUTabR = NULL;
    ui_IMUYawRollLabelR = NULL;
    ui_DevBackButton = NULL;
    ui_DevBackButtonText = NULL;
    ui_DevMiniStatusBarR = NULL;
    ui_DevConStatusContainerR = NULL;
    ui_DevLRecvLabelR = NULL;
    ui_DevLRLabelR = NULL;
    ui_DevRRecvLabelR = NULL;
    ui_DevMiniModeLabelR = NULL;
    ui_DevMiniBarBatteryContainerR = NULL;
    ui_RDevMiniBatteryLabelL = NULL;
    ui_RDevMiniBatteryLevelLabelL = NULL;
    ui_RDevMiniBatteryLabelR = NULL;
    ui_RDevMiniBatteryLevelLabelR = NULL;
    ui_DevScreenRButtonRight = NULL;
    ui_DevScreenRButtonRightLabel = NULL;
    ui_DevScreenRMainLabelPanel = NULL;
    ui_DevScreenRMainLabel = NULL;

}
