// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_StatusBar = NULL;
lv_obj_t * ui_ConStatusLabel = NULL;
lv_obj_t * ui_BatteryContainer = NULL;
lv_obj_t * ui_BatteryLabelL = NULL;
lv_obj_t * ui_BatteryLevelLabelL = NULL;
lv_obj_t * ui_BatteryLabelR = NULL;
lv_obj_t * ui_BatteryLevelLabelR = NULL;
lv_obj_t * ui_ModeLabel = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_SettingsText = NULL;
lv_obj_t * ui_DevViewButton = NULL;
lv_obj_t * ui_DevViewText = NULL;
// event funtions
void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_DevViewButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DevScreenR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DevScreenR_screen_init);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBar = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_StatusBar, 312);
    lv_obj_set_height(ui_StatusBar, 50);
    lv_obj_set_x(ui_StatusBar, 0);
    lv_obj_set_y(ui_StatusBar, -91);
    lv_obj_set_align(ui_StatusBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_StatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_StatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_StatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_StatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_StatusBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StatusBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConStatusLabel = lv_label_create(ui_StatusBar);
    lv_obj_set_width(ui_ConStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConStatusLabel, -1);
    lv_obj_set_y(ui_ConStatusLabel, 1);
    lv_label_set_text(ui_ConStatusLabel, "ESP-NOW");
    lv_obj_set_style_text_color(ui_ConStatusLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConStatusLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConStatusLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryContainer = lv_obj_create(ui_StatusBar);
    lv_obj_remove_style_all(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryContainer, 60);
    lv_obj_set_height(ui_BatteryContainer, 40);
    lv_obj_set_x(ui_BatteryContainer, 3);
    lv_obj_set_y(ui_BatteryContainer, -10);
    lv_obj_set_align(ui_BatteryContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_BatteryContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_BatteryLabelL = lv_label_create(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabelL, -39);
    lv_obj_set_y(ui_BatteryLabelL, -9);
    lv_obj_set_align(ui_BatteryLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BatteryLabelL, "L:");
    lv_obj_set_style_text_color(ui_BatteryLabelL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BatteryLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryLabelL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryLevelLabelL = lv_label_create(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryLevelLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLevelLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLevelLabelL, 0);
    lv_obj_set_y(ui_BatteryLevelLabelL, -9);
    lv_obj_set_align(ui_BatteryLevelLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BatteryLevelLabelL, "100%");
    lv_obj_set_style_text_color(ui_BatteryLevelLabelL, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLevelLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BatteryLevelLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryLevelLabelL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryLabelR = lv_label_create(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabelR, -39);
    lv_obj_set_y(ui_BatteryLabelR, 10);
    lv_obj_set_align(ui_BatteryLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BatteryLabelR, "R:");
    lv_obj_set_style_text_color(ui_BatteryLabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BatteryLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryLabelR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryLevelLabelR = lv_label_create(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryLevelLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLevelLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLevelLabelR, 0);
    lv_obj_set_y(ui_BatteryLevelLabelR, 10);
    lv_obj_set_align(ui_BatteryLevelLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BatteryLevelLabelR, "100%");
    lv_obj_set_style_text_color(ui_BatteryLevelLabelR, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLevelLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BatteryLevelLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryLevelLabelR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_ModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeLabel, "MODE");
    lv_obj_clear_flag(ui_ModeLabel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_ModeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ModeLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_SettingsButton, 81);
    lv_obj_set_height(ui_SettingsButton, 40);
    lv_obj_set_x(ui_SettingsButton, 113);
    lv_obj_set_y(ui_SettingsButton, 97);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_SettingsButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsText = lv_label_create(ui_SettingsButton);
    lv_obj_set_width(ui_SettingsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsText, "Settings");
    lv_obj_set_style_text_color(ui_SettingsText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevViewButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_DevViewButton, 81);
    lv_obj_set_height(ui_DevViewButton, 40);
    lv_obj_set_x(ui_DevViewButton, -113);
    lv_obj_set_y(ui_DevViewButton, 97);
    lv_obj_set_align(ui_DevViewButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DevViewButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DevViewButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevViewButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevViewButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevViewText = lv_label_create(ui_DevViewButton);
    lv_obj_set_width(ui_DevViewText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevViewText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevViewText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevViewText, "Dev View");
    lv_obj_set_style_text_color(ui_DevViewText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevViewText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DevViewButton, ui_event_DevViewButton, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_StatusBar = NULL;
    ui_ConStatusLabel = NULL;
    ui_BatteryContainer = NULL;
    ui_BatteryLabelL = NULL;
    ui_BatteryLevelLabelL = NULL;
    ui_BatteryLabelR = NULL;
    ui_BatteryLevelLabelR = NULL;
    ui_ModeLabel = NULL;
    ui_SettingsButton = NULL;
    ui_SettingsText = NULL;
    ui_DevViewButton = NULL;
    ui_DevViewText = NULL;

}
