// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_HomeStatusBar;
extern lv_obj_t * ui_HomeLRecvConLabel;
extern lv_obj_t * ui_HomeRRecvConLabel;
extern lv_obj_t * ui_HomeLRConLabel;
extern lv_obj_t * ui_HomeBatteryContainer;
extern lv_obj_t * ui_HomeBatteryLabelL;
extern lv_obj_t * ui_HomeBatteryLevelLabelL;
extern lv_obj_t * ui_HomeBatteryLabelR;
extern lv_obj_t * ui_HomeBatteryLevelLabelR;
extern lv_obj_t * ui_HomeModeLabel;
extern void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_SettingsText;
extern void ui_event_DevViewButton(lv_event_t * e);
extern lv_obj_t * ui_DevViewButton;
extern lv_obj_t * ui_DevViewText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

