// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_StatusBar;
extern lv_obj_t * ui_ConStatusLabel;
extern lv_obj_t * ui_BatteryContainer;
extern lv_obj_t * ui_BatteryLabelL;
extern lv_obj_t * ui_BatteryLevelLabelL;
extern lv_obj_t * ui_BatteryLabelR;
extern lv_obj_t * ui_BatteryLevelLabelR;
extern lv_obj_t * ui_ModeLabel;
extern void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_SettingsText;
extern void ui_event_DevViewButton(lv_event_t * e);
extern lv_obj_t * ui_DevViewButton;
extern lv_obj_t * ui_DevViewText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

