// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_SplashScreen = NULL;
lv_obj_t * ui_SplashScreenPanel = NULL;
lv_obj_t * ui_SplashScreenLabel = NULL;
// event funtions

// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SplashScreenPanel = lv_obj_create(ui_SplashScreen);
    lv_obj_set_width(ui_SplashScreenPanel, 296);
    lv_obj_set_height(ui_SplashScreenPanel, 220);
    lv_obj_set_align(ui_SplashScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SplashScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SplashScreenPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_SplashScreenPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_SplashScreenPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_SplashScreenPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_SplashScreenPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SplashScreenPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplashScreenLabel = lv_label_create(ui_SplashScreenPanel);
    lv_obj_set_width(ui_SplashScreenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplashScreenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SplashScreenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SplashScreenLabel, "INITIALIZING\nSENSORS");
    lv_obj_set_style_text_color(ui_SplashScreenLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SplashScreenLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SplashScreenLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SplashScreenLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SplashScreen = NULL;
    ui_SplashScreenPanel = NULL;
    ui_SplashScreenLabel = NULL;

}
