// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_TempSettingsLabel = NULL;
lv_obj_t * ui_MainButtonTemplate = NULL;
lv_obj_t * ui_BackLabel1 = NULL;
// event funtions
void ui_event_MainButtonTemplate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempSettingsLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_TempSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempSettingsLabel, "SETTINGS\nNOTHING HERE RIGHT NOW");
    lv_obj_set_style_text_color(ui_TempSettingsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempSettingsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TempSettingsLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainButtonTemplate = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_MainButtonTemplate, 81);
    lv_obj_set_height(ui_MainButtonTemplate, 40);
    lv_obj_set_x(ui_MainButtonTemplate, -113);
    lv_obj_set_y(ui_MainButtonTemplate, 97);
    lv_obj_set_align(ui_MainButtonTemplate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainButtonTemplate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MainButtonTemplate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_MainButtonTemplate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_MainButtonTemplate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MainButtonTemplate, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel1 = lv_label_create(ui_MainButtonTemplate);
    lv_obj_set_width(ui_BackLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel1, "Back");
    lv_obj_set_style_text_color(ui_BackLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainButtonTemplate, ui_event_MainButtonTemplate, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_TempSettingsLabel = NULL;
    ui_MainButtonTemplate = NULL;
    ui_BackLabel1 = NULL;

}
