// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_TempSettingsLabel = NULL;
lv_obj_t * ui_MainButtonTemplate1 = NULL;
lv_obj_t * ui_BackLabel = NULL;
// event funtions
void ui_event_MainButtonTemplate1_MainButtonTemplate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 150, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempSettingsLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_TempSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempSettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempSettingsLabel, "SETTINGS\nNOTHING HERE RIGHT NOW");
    lv_obj_set_style_text_color(ui_TempSettingsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempSettingsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TempSettingsLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainButtonTemplate1 = ui_MainButtonTemplate_create(ui_Settings);
    lv_obj_set_x(ui_MainButtonTemplate1, -113);
    lv_obj_set_y(ui_MainButtonTemplate1, 97);

    ui_BackLabel = lv_label_create(ui_MainButtonTemplate1);
    lv_obj_set_width(ui_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel, "Back");
    lv_obj_set_style_text_color(ui_BackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_BackLabel, 0);
    lv_obj_add_event_cb(ui_MainButtonTemplate1, ui_event_MainButtonTemplate1_MainButtonTemplate, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_TempSettingsLabel = NULL;
    ui_MainButtonTemplate1 = NULL;
    ui_BackLabel = NULL;

}
