// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef UI_DEVSCREENL_H
#define UI_DEVSCREENL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DevScreenL
extern void ui_DevScreenL_screen_init(void);
extern void ui_DevScreenL_screen_destroy(void);
extern lv_obj_t * ui_DevScreenL;
extern lv_obj_t * ui_DevTabViewL;
extern lv_obj_t * ui_FSRTabL;
extern lv_obj_t * ui_FSRIndexLabelL;
extern lv_obj_t * ui_FSRReadingsLabelL;
extern lv_obj_t * ui_FSRBarContainerL;
extern lv_obj_t * ui_FSR0BarL;
extern lv_obj_t * ui_FSR1BarL;
extern lv_obj_t * ui_FSR2BarL;
extern lv_obj_t * ui_FSR3BarL;
extern lv_obj_t * ui_FSR4BarL;
extern lv_obj_t * ui_FlexTabL;
extern lv_obj_t * ui_FlexIndexLabelL;
extern lv_obj_t * ui_FlexReadingsLabelL;
extern lv_obj_t * ui_FlexBarContainerL;
extern lv_obj_t * ui_Flex5BarL;
extern lv_obj_t * ui_Flex6BarL;
extern lv_obj_t * ui_Flex7BarL;
extern lv_obj_t * ui_Flex8BarL;
extern lv_obj_t * ui_Flex9BarL;
extern lv_obj_t * ui_Flex10BarL;
extern lv_obj_t * ui_Flex11BarL;
extern lv_obj_t * ui_IMUTabL;
extern lv_obj_t * ui_IMUYawRollLabelL;
extern lv_obj_t * ui_DevMiniStatusBarL;
extern lv_obj_t * ui_DevConStatusContainerL;
extern lv_obj_t * ui_DevLRecvLabelL;
extern lv_obj_t * ui_DevLRLabelL;
extern lv_obj_t * ui_DevRRecvLabelL;
extern lv_obj_t * ui_DevMiniModeLabelL;
extern lv_obj_t * ui_DevMiniBarBatteryContainerL;
extern lv_obj_t * ui_LDevMiniBatteryLabelL;
extern lv_obj_t * ui_LDevMiniBatteryLevelLabelL;
extern lv_obj_t * ui_LDevMiniBatteryLabelR;
extern lv_obj_t * ui_LDevMiniBatteryLevelLabelR;
extern lv_obj_t * ui_DevScreenLButtonRight;
extern lv_obj_t * ui_DevScreenLButtonRightLabel;
extern void ui_event_DevScreenLButtonLeft(lv_event_t * e);
extern lv_obj_t * ui_DevScreenLButtonLeft;
extern lv_obj_t * ui_DevScreenLButtonLeftLabel;
extern lv_obj_t * ui_DevScreenLMainLabelPanel;
extern lv_obj_t * ui_DevScreenLMainLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

