// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_HomeStatusBar = NULL;
lv_obj_t * ui_HomeLRecvConLabel = NULL;
lv_obj_t * ui_HomeRRecvConLabel = NULL;
lv_obj_t * ui_HomeLRConLabel = NULL;
lv_obj_t * ui_HomeBatteryContainer = NULL;
lv_obj_t * ui_HomeBatteryLabelL = NULL;
lv_obj_t * ui_HomeBatteryLevelLabelL = NULL;
lv_obj_t * ui_HomeBatteryLabelR = NULL;
lv_obj_t * ui_HomeBatteryLevelLabelR = NULL;
lv_obj_t * ui_HomeModeLabel = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_SettingsText = NULL;
lv_obj_t * ui_DevViewButton = NULL;
lv_obj_t * ui_DevViewText = NULL;
// event funtions
void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_DevViewButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DevScreenR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DevScreenR_screen_init);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeStatusBar = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_HomeStatusBar, 312);
    lv_obj_set_height(ui_HomeStatusBar, 50);
    lv_obj_set_x(ui_HomeStatusBar, 0);
    lv_obj_set_y(ui_HomeStatusBar, -91);
    lv_obj_set_align(ui_HomeStatusBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeStatusBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HomeStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_HomeStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_HomeStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_HomeStatusBar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_HomeStatusBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeStatusBar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLRecvConLabel = lv_label_create(ui_HomeStatusBar);
    lv_obj_set_width(ui_HomeLRecvConLabel, 83);
    lv_obj_set_height(ui_HomeLRecvConLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLRecvConLabel, -7);
    lv_obj_set_y(ui_HomeLRecvConLabel, -2);
    lv_label_set_text(ui_HomeLRecvConLabel, "L<>RECV: \nDISCONNECTED");
    lv_obj_set_style_text_color(ui_HomeLRecvConLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLRecvConLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeLRecvConLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLRecvConLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeRRecvConLabel = lv_label_create(ui_HomeStatusBar);
    lv_obj_set_width(ui_HomeRRecvConLabel, 83);
    lv_obj_set_height(ui_HomeRRecvConLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeRRecvConLabel, 80);
    lv_obj_set_y(ui_HomeRRecvConLabel, -2);
    lv_label_set_text(ui_HomeRRecvConLabel, "R<>RECV: \nDISCONNECTED");
    lv_obj_set_style_text_color(ui_HomeRRecvConLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeRRecvConLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeRRecvConLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeRRecvConLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeLRConLabel = lv_label_create(ui_HomeStatusBar);
    lv_obj_set_width(ui_HomeLRConLabel, 83);
    lv_obj_set_height(ui_HomeLRConLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeLRConLabel, 167);
    lv_obj_set_y(ui_HomeLRConLabel, -2);
    lv_label_set_text(ui_HomeLRConLabel, "L<>R: \nDISCONNECTED");
    lv_obj_set_style_text_color(ui_HomeLRConLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeLRConLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeLRConLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeLRConLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBatteryContainer = lv_obj_create(ui_HomeStatusBar);
    lv_obj_remove_style_all(ui_HomeBatteryContainer);
    lv_obj_set_width(ui_HomeBatteryContainer, 38);
    lv_obj_set_height(ui_HomeBatteryContainer, 40);
    lv_obj_set_x(ui_HomeBatteryContainer, 11);
    lv_obj_set_y(ui_HomeBatteryContainer, -11);
    lv_obj_set_align(ui_HomeBatteryContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_HomeBatteryContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_HomeBatteryContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_HomeBatteryContainer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_HomeBatteryContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeBatteryContainer, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBatteryLabelL = lv_label_create(ui_HomeBatteryContainer);
    lv_obj_set_width(ui_HomeBatteryLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBatteryLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeBatteryLabelL, -26);
    lv_obj_set_y(ui_HomeBatteryLabelL, -9);
    lv_obj_set_align(ui_HomeBatteryLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HomeBatteryLabelL, "L:");
    lv_obj_set_style_text_color(ui_HomeBatteryLabelL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBatteryLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBatteryLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBatteryLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBatteryLevelLabelL = lv_label_create(ui_HomeBatteryContainer);
    lv_obj_set_width(ui_HomeBatteryLevelLabelL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBatteryLevelLabelL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeBatteryLevelLabelL, 1);
    lv_obj_set_y(ui_HomeBatteryLevelLabelL, -9);
    lv_obj_set_align(ui_HomeBatteryLevelLabelL, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HomeBatteryLevelLabelL, "100%");
    lv_obj_set_style_text_color(ui_HomeBatteryLevelLabelL, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBatteryLevelLabelL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBatteryLevelLabelL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBatteryLevelLabelL, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBatteryLabelR = lv_label_create(ui_HomeBatteryContainer);
    lv_obj_set_width(ui_HomeBatteryLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBatteryLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeBatteryLabelR, -26);
    lv_obj_set_y(ui_HomeBatteryLabelR, 10);
    lv_obj_set_align(ui_HomeBatteryLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HomeBatteryLabelR, "R:");
    lv_obj_set_style_text_color(ui_HomeBatteryLabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBatteryLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBatteryLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBatteryLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBatteryLevelLabelR = lv_label_create(ui_HomeBatteryContainer);
    lv_obj_set_width(ui_HomeBatteryLevelLabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBatteryLevelLabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeBatteryLevelLabelR, 1);
    lv_obj_set_y(ui_HomeBatteryLevelLabelR, 10);
    lv_obj_set_align(ui_HomeBatteryLevelLabelR, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HomeBatteryLevelLabelR, "100%");
    lv_obj_set_style_text_color(ui_HomeBatteryLevelLabelR, lv_color_hex(0x31FF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBatteryLevelLabelR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBatteryLevelLabelR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBatteryLevelLabelR, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeModeLabel = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_HomeModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeModeLabel, "MODE");
    lv_obj_clear_flag(ui_HomeModeLabel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_HomeModeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeModeLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_SettingsButton, 81);
    lv_obj_set_height(ui_SettingsButton, 40);
    lv_obj_set_x(ui_SettingsButton, 113);
    lv_obj_set_y(ui_SettingsButton, 97);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_SettingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_SettingsButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsText = lv_label_create(ui_SettingsButton);
    lv_obj_set_width(ui_SettingsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsText, "Settings");
    lv_obj_set_style_text_color(ui_SettingsText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevViewButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_DevViewButton, 81);
    lv_obj_set_height(ui_DevViewButton, 40);
    lv_obj_set_x(ui_DevViewButton, -113);
    lv_obj_set_y(ui_DevViewButton, 97);
    lv_obj_set_align(ui_DevViewButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DevViewButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DevViewButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FieldBG);
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FieldBG);
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_FieldBorder);
    ui_object_set_themeable_style_property(ui_DevViewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_FieldBorder);
    lv_obj_set_style_border_width(ui_DevViewButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DevViewButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevViewText = lv_label_create(ui_DevViewButton);
    lv_obj_set_width(ui_DevViewText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DevViewText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DevViewText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DevViewText, "Dev View");
    lv_obj_set_style_text_color(ui_DevViewText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DevViewText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DevViewButton, ui_event_DevViewButton, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_HomeStatusBar = NULL;
    ui_HomeLRecvConLabel = NULL;
    ui_HomeRRecvConLabel = NULL;
    ui_HomeLRConLabel = NULL;
    ui_HomeBatteryContainer = NULL;
    ui_HomeBatteryLabelL = NULL;
    ui_HomeBatteryLevelLabelL = NULL;
    ui_HomeBatteryLabelR = NULL;
    ui_HomeBatteryLevelLabelR = NULL;
    ui_HomeModeLabel = NULL;
    ui_SettingsButton = NULL;
    ui_SettingsText = NULL;
    ui_DevViewButton = NULL;
    ui_DevViewText = NULL;

}
