// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern void ui_event_MainButtonTemplate(lv_event_t * e);
extern lv_obj_t * ui_MainButtonTemplate;
extern lv_obj_t * ui_BackLabel1;
extern lv_obj_t * ui_SettingsStatusBar;
extern lv_obj_t * ui_SettingsLRecvConLabel;
extern lv_obj_t * ui_SettingsRRecvConLabel;
extern lv_obj_t * ui_SettingsLRConLabel;
extern lv_obj_t * ui_SettingsBatteryContainer;
extern lv_obj_t * ui_SettingsBatteryLabelL;
extern lv_obj_t * ui_SettingsBatteryLevelLabelL;
extern lv_obj_t * ui_SettingsBatteryLabelR;
extern lv_obj_t * ui_SettingsBatteryLevelLabelR;
extern void ui_event_InitiateCommsButton(lv_event_t * e);
extern lv_obj_t * ui_InitiateCommsButton;
extern lv_obj_t * ui_BackLabel2;
extern lv_obj_t * ui_SettingsModePanel;
extern lv_obj_t * ui_SettingsModeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

