// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DataGloveUI

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_FieldBG[1] = {0x3F71FF};
const ui_theme_variable_t _ui_theme_alpha_FieldBG[1] = {255};

const ui_theme_variable_t _ui_theme_color_FieldBorder[1] = {0xE7D02D};
const ui_theme_variable_t _ui_theme_alpha_FieldBorder[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

